# Høje Taastrup PTES data for 2024

In [1]:
import pandas as pd
import numpy as np

In [2]:
# Function definition for calculating the water density and specific heat as a function of temperature
def density_water(T):
    '''Calculates density (rho) of water in kg/m^3 based on fluid temperature (T) nearest the flow meter in degrees Celsius'''
    rho = (999.85+5.332*(10**-2)*T-7.564*(10**-3)*(T**2)+4.323*(10**-5)*(T**3)-1.673*(10**-7)*(T**4)+2.447*(10**-10)*(T**5))
    return(rho)

def specific_heat_water(T):
    '''Calculates specific heat (cp) of water in J/(kg K) based on mean fluid temperature (T) in degrees Celsius'''
    cp = (4.2184-2.8218*(10**-3)*T+7.3478*(10**-5)*(T**2)-9.4712*(10**-7)*(T**3)+7.2869*(10**-9)*(T**4)-2.8098*(10**-11)*(T**5)
          +4.4008*(10**-14)*(T**6))*1000
    return(cp)

### Read data

In [3]:
df = pd.read_csv('C:/Users/iosif/OneDrive - Danmarks Tekniske Universitet/Skrivebord/HT_data_for_github.csv', index_col=[0])
df.index = pd.to_datetime(df.index)
# plot the first 5 rows of the dataframe for inspection
df.head()

,A_00.25m,A_00.75m,A_01.25m,A_02.00m,A_03.00m,A_04.00m,A_05.00m,A_06.00m,A_06.50m,A_08.50m,...,F_bot,F_mid,T_bot_0.2m,T_bot_1.2m,T_bot_2.2m,T_amb,air_humidity,wind_speed,water_level_guided_radar,water_level_pressure
time,,,,,,,,,,,,,,,,,,,,,
2024-01-01 00:00:00+00:00,86.13704,87.602240,87.38460,86.296880,78.830574,63.479780,53.837936,52.227260,52.289753,51.852394,...,0.0,-0.0,50.102818,51.761597,50.642357,5.098751,100.0,3.9,36.672623,36.697613
2024-01-01 00:01:00+00:00,86.12564,87.601860,87.38418,86.296616,78.830154,63.479702,53.837746,52.227146,52.289867,51.852203,...,0.0,-0.0,50.102530,51.761500,50.641880,5.100001,100.0,4.5,36.672620,36.696445
2024-01-01 00:02:00+00:00,86.11425,87.601480,87.38376,86.296350,78.829735,63.479626,53.837555,52.227030,52.289980,51.852013,...,0.0,-0.0,50.102245,51.761406,50.641403,5.101251,100.0,3.2,36.672615,36.696873
2024-01-01 00:03:00+00:00,86.10285,87.601100,87.38334,86.296160,78.829315,63.479550,53.837364,52.226917,52.290096,51.851820,...,0.0,-0.0,50.101960,51.761310,50.640926,5.102501,100.0,3.6,36.672610,36.696976
2024-01-01 00:04:00+00:00,86.09146,87.600716,87.38292,86.295970,78.828896,63.479473,53.837173,52.226803,52.290210,51.851630,...,0.0,-0.0,50.101673,51.761215,50.640450,5.103751,100.0,4.0,36.672607,36.696873

In [4]:
# Make a list with all the temperature sensors in location A
A_strings = [c for c in df.columns if c.startswith('A')]
A_strings.sort()

# Make a list with all the temperature sensors in location B
B_strings = [c for c in df.columns if c.startswith('B')]
B_strings.sort()

# Group the ground temperature strings
ground_temp = [c for c in df.columns if c.startswith('T_ground')]

# Temperature sensors attached to the bottom of the storage
bottom_temp = ['T_bot_0.2m', 'T_bot_1.2m', 'T_bot_2.2m']

# make a list of all sensors measuring temperature in the storage
temperature_sensors = A_strings + B_strings + bottom_temp

In [5]:
# Ensure that all relative humidity measurements are always between 0-100 %
df.loc[(df['air_humidity']>100) | (df['air_humidity']<=0), 'air_humidity'] = np.nan
df.loc[(df['lid_humidity_1_1']>100) | (df['lid_humidity_1_1']<=0), 'lid_humidity_1_1'] = np.nan
df.loc[(df['lid_humidity_1_2']>100) | (df['lid_humidity_1_2']<=0), 'lid_humidity_1_2'] = np.nan
df.loc[(df['lid_humidity_2_1']>100) | (df['lid_humidity_2_1']<=0), 'lid_humidity_2_1'] = np.nan
df.loc[(df['lid_humidity_2_2']>100) | (df['lid_humidity_2_2']<=0), 'lid_humidity_2_2'] = np.nan

# Ensure that wind speed is never above 100 m/s
df.loc[df['wind_speed']>100, 'wind_speed'] = np.nan

# Ensure that all PTES water measurements are between 0 and 100 degC
for sensor in temperature_sensors:
    df.loc[(df[sensor]>100) | (df[sensor]<0), sensor] = np.nan

### Storage efficiency calculation

In [6]:
# The volumes were calculated from a 3D model of the PTES made in ANSYS Fluent.
# The volume of each layer was specified based on the distance between the temperature sensors.
# Each sensor measures at the middle of each layer.

volumes = [
    2018.9,
    2638.2,
    2577.4,
    2517.1,
    2457.3,
    4157.8,
    4533.7,
    4305.1,
    4080.9,
    3860.9,
    3645.3,
    3434,
    3227,
    3024.1,
    2826.8,
    4482.8,
    4426.1,
    2403.9,
    1727.6,
    1559.4,
    3191.1,
    1452,
    763.63,
    453.54,
    607.28,
    259.35
]

volume_per_layer = pd.Series(volumes).round(1)
volume_per_layer.sum()

70631.2

In [7]:
# Fill in the gaps by interpolation
df[A_strings] = df[A_strings].interpolate(axis=1, limit_direction='both')
df[A_strings] = df[A_strings].interpolate(axis=0, limit_direction='both')

# Check if there are any NaN values left in the dataset
print('Nan values = {}'.format(df[A_strings].isna().sum().sum()))

Nan values = 0

In [8]:
T_ref = 48.5 # This value was used for the feasibility calculations
# Calculate the energy content per volume
heat_per_volume = df[A_strings].apply(density_water) * df[A_strings].apply(specific_heat_water) * (df[A_strings]-T_ref)

# Calculate the energy content per layer
heat_per_layer = heat_per_volume.multiply(list(volume_per_layer), axis='columns').divide(3600).divide(10**6) # MWh/layer

# Sum them up for the total energy content of the storage
Q_storage = heat_per_layer.sum(axis='columns')

In [9]:
# calculate the monthly internal energy change
eff_freq = '1ME'
content_2023 = pd.Series(data=Q_storage.iloc[0], index=[pd.Timestamp('2023-12-31', tz='UTC')])
Q_internal_energy_change = pd.concat([Q_storage, content_2023]).resample(eff_freq).last().diff(1).iloc[1:]

In [10]:
# create a new monthly dataframe for finding the monthly energy efficiency
monthly = df[['E_discharge','E_charge']].resample(eff_freq).sum()
monthly['Delta_Q'] = Q_internal_energy_change

monthly['efficiency [%]'] = (monthly['E_discharge'] / (monthly['E_charge'] - monthly['Delta_Q']) *100).round(0)
monthly

,E_discharge,E_charge,Delta_Q,efficiency [%]
time,,,,
2024-01-31 00:00:00+00:00,1628.832545,1396.399593,-434.171542,89.0
2024-02-29 00:00:00+00:00,2297.269569,2960.623110,214.528325,84.0
2024-03-31 00:00:00+00:00,4307.128367,4993.206022,267.928384,91.0
2024-04-30 00:00:00+00:00,3900.622691,3793.129338,-321.647312,95.0
2024-05-31 00:00:00+00:00,2160.709806,3612.519960,994.310191,83.0
2024-06-30 00:00:00+00:00,2111.625602,1361.652460,-893.854133,94.0
2024-07-31 00:00:00+00:00,1299.428151,2660.036659,959.867899,76.0
2024-08-31 00:00:00+00:00,1533.560253,768.441658,-979.605173,88.0
2024-09-30 00:00:00+00:00,1869.574886,1388.063543,-640.773920,92.0
2024-10-31 00:00:00+00:00,278.582844,54.294417,-235.714647,96.0

In [11]:
eff = (monthly['E_discharge'].sum() / (monthly['E_charge'].sum() - monthly['Delta_Q'].sum()) *100).round(0)
print(f'The yearly efficiency for 2024 is: {eff} %')

The yearly efficiency for 2024 is: 89.0 %